// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 31/7/2025, 4:58:21 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["E:/assessment project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/assessment project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/assessment project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/assessment project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/assessment project/plugins/**/*.{js,ts,mjs}","E:/assessment project/composables/**/*.{js,ts,mjs}","E:/assessment project/utils/**/*.{js,ts,mjs}","E:/assessment project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/assessment project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/assessment project/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;